### ISSUE TITLE
remote monitoring is not working

### ISSUE THREAD

**Issue by FullDataAlchemist** [bloomberg/memray#180] opened 2022-08-13 08:42 UTC
## Bug Report

Remote monitoring is not working :(
I use two ways for remote monitoring on my local machine. I am using ubuntu 20.04 with python3.8

### 1 - Use Socket Destination in code
I use this sample code:
```
main():
    while True:
        print("DO JOB")

if __name__ == '__main__':
    socket_dist = SocketDestination(server_port=<port>, address='127.0.0.1')  # or even 0.0.0.0 
    with Tracker(destination=socket_dist):
        main()
```
two issues are happening here : 
1- the code is not working (printing) until I run `memray3.8 live 35907` in another shell
2- when I run `memray3.8 live 35907` nothing shows [this image](https://drive.google.com/file/d/1ONKJtReH2yOf19aJymqTu_uXFxNsqq-E/view?usp=sharing)

### 2 - Use Live Remote in the shell and use the port in another shell
I use `memray run --live-remote test-memary.py`
and use `memray live <port>`
two issues are happening here : 
1- the results are fixed values! I used `memray run --live test-memary.py` for comparing the results and its completely different! `memray run --live test-memary.py` shows different locations and they are changing and updating but in the remote running as I described above all the values are fixed and not changing at all!
2- the code is not working (printing in this code) until I run `memray live <port>` and it seems that this code trigger to run! and after killing the `memray live <port>` and rerun again it shows nothing! seems that it should be run from the first place and this issue is not good for long-running monitoring! 

so that any kind of remote monitoring is not working!

**Environment**
- python3.8

**Comment by pablogsal** [comment] 2022-08-13 17:41
Hi @FullDataAlchemist and thank you for the report. Let me cover your points:

**Comment by pablogsal** [comment] 2022-08-13 17:47
I'm closing this issue as it seems is not a bug but some misconceptions regarding how to use the tool, but please, feel free to continue the discussion.

**Closed by pablogsal** 2022-08-13 17:47 UTC
