### ISSUE TITLE
gcc/4.7.2/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18'

### ISSUE THREAD

**Issue by nbahar-intel** [bloomberg/memray#148] opened 2022-06-16 18:45 UTC
## Bug Report

**Current Behavior** A clear and concise description of the behavior.
When running my package, which uses a pre-built c packages as-well, it fails on GLIBC stuff.
When I run my package standalone without memray, it does work.

```
ImportError: /***/pkgs/gcc/4.7.2/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by ***.cpython-37m-x86_64-linux-gnu.so)
```

**Input Code**

- REPL or Repo link if applicable:
Not applicable

**Expected behavior/code** A clear and concise description of what you expected to happen (or
code).

It should run the same as running my main module

**Environment**

- Python(s): Python 3.7.4

**Possible Solution**

**Additional context/Screenshots** Add any other context about the problem here. If applicable, add
screenshots to help explain.

**Comment by godlygeek** [comment] 2022-06-17 17:31
GCC 4.7.2 is from 2012, and Memray is written in C++17. The earliest version of GCC that even began to implement C++17 features was GCC 5.

**Comment by godlygeek** [comment] 2022-06-22 15:56
I think I've diagnosed this incorrectly - I've downloaded our 3.7 wheel, and confirmed that it does not depend on `GLIBCXX_3.4.18` (the highest versioned symbols it requires are provided by `GLIBCXX_3.4.11`). Which means that dependency is coming from your module, not ours, and the version of `libstdc++` that your library is compiled against is not compatible with the version of `libstdc++` that it winds up being linked against at runtime.

I think what's going wrong is that your system has multiple copies of `libstdc++` on it, and when your extension module works, it's because you are getting it to load some non-default version of `libstdc++` (possibly with `LD_LIBRARY_PATH`, or possibly with `-Wl,-rpath` when you link it). When Memray (or any other C++ extension) gets loaded first, the version of `libstdc++` that gets loaded will be the one provided by the system, but when your extension gets loaded first, it's somehow forcing a different version of `libstdc++` to be pulled in.

If you take your `***.cpython-37m-x86_64-linux-gnu.so` and run:
```
readelf -a memray/_memray.cpython-37m-x86_64-linux-gnu.so | egrep '(PATH|libstdc|Name: GLIBCXX)'
```
what output do you get? Does it include a dependency on `GLIBCXX_3.4.18`?

If the output contains a `Library rpath` line, does a `libstdc++` exist in that directory? If not, can you check whether you're setting `LD_LIBRARY_PATH` somewhere in your Python code before you load your extension module?

**Comment by godlygeek** [comment] 2022-06-22 19:35
Well, that `***` that you've redacted is important - what is in that directory? Does that directory contain a `libstdc++.so.6` that is different from the `/***/pkgs/gcc/4.7.2/lib64/libstdc++.so.6` that you mentioned in your initial post?

**Comment by nbahar-intel** [comment] 2022-06-22 20:01
Folder does not contain libstdc++.so.6
Here is a more informative library runpath:
Library runpath: Library runpath: `[/../pugixml/1.11/_/_/package/lib:/../boost/1.75.0/_/_/package/lib:/../pybind11/2.6.2/lib:/../zlib/1.2.11/lib:/../bzip2/1.0.8/lib:/../cci.20210118/lib]`

**Comment by godlygeek** [comment] 2022-06-22 20:13
And none of those colon-separated directories contain a `libstdc++.so.6`? Hm, that's not what I was expecting to find.

OK, let's try a different direction: try importing your module into a Python interpreter and then doing
```py
print("".join(line for line in open("/proc/self/maps") if "libstdc++" in line)
```

You should get some output that looks roughly like:
```text
7f7b4667d000-7f7b46766000 r-xp 00000000 08:20 6486                       /usr/lib64/libstdc++.so.6.0.19
7f7b46766000-7f7b46966000 ---p 000e9000 08:20 6486                       /usr/lib64/libstdc++.so.6.0.19
7f7b46966000-7f7b4696e000 r--p 000e9000 08:20 6486                       /usr/lib64/libstdc++.so.6.0.19
7f7b4696e000-7f7b46970000 rw-p 000f1000 08:20 6486                       /usr/lib64/libstdc++.so.6.0.19
```

What is the path in the last column for you? Presumably it's not the `/***/pkgs/gcc/4.7.2/lib64/libstdc++.so.6` that you mentioned in your first post, so the question is what it is and where it's coming from.

**Comment by godlygeek** [comment] 2022-07-25 19:55
There's nothing further I can do to help debug this without more information from the issue submitter. I'm going to close this since there haven't been any updates in over a month and the issue does not appear to be with Memray, but rather with the way the OP's other package is built.

**Closed by godlygeek** 2022-07-25 19:55 UTC

**Comment by nbahar-intel** [comment] 2022-07-25 20:05
I appreciate it. For now, let's keep this one closed.
