### ISSUE TITLE
AssertionError when generating flamegraph from native run

### ISSUE THREAD

**Issue by toofar** [bloomberg/memray#332] opened 2023-03-11 06:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to generation a flamegraph based on data from a native run. I'm getting this output:

```
⚠  No debug information was found for the Python interpreter  ⚠

Without debug information reports showing native traces may not include file names and line numbers. Please use an interpreter 
built with debug symbols for best results. Check https://bloomberg.github.io/memray/native_mode.html for more information 
regarding how memray resolves symbols.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/mnt/ssd/user/qute-basedirs/venv-6.5/lib/python3.11/site-packages/memray/__main__.py", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/mnt/ssd/user/qute-basedirs/venv-6.5/lib/python3.11/site-packages/memray/commands/__init__.py", line 128, in main
    arg_values.entrypoint(arg_values, parser)
  File "/mnt/ssd/user/qute-basedirs/venv-6.5/lib/python3.11/site-packages/memray/commands/common.py", line 165, in run
    self.write_report(
  File "/mnt/ssd/user/qute-basedirs/venv-6.5/lib/python3.11/site-packages/memray/commands/common.py", line 130, in write_report
    reporter = self.reporter_factory(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd/user/qute-basedirs/venv-6.5/lib/python3.11/site-packages/memray/reporters/flamegraph.py", line 121, in from_snapshot
    tuple(record.hybrid_stack_trace())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/memray/_memray.pyx", line 279, in memray._memray.AllocationRecord.hybrid_stack_trace
AssertionError
```

The .bin file is here (50MB): https://litter.catbox.moe/g8io46.bin
It's a 3 day link, I can put up another one if that times out.

I'm on python 3.11 (debian version  3.11.2-1 from unstable). I was trying to trace memory usage in qutebrowser (PyQt and QtWebEngine) using the script on [this comment](https://github.com/qutebrowser/qutebrowser/issues/1476#issuecomment-1152868011) (with a couple of modification like adding `--native` to the memray call and setting DEBUGINFOD_URLS). pip freeze reports `memray==1.7.0`

I can do more to help you reproduce the trace run, or find a more minimal reproducer. But I'm hoping the .bin file is enough.

### Expected Behavior

I get an attractive and informative flamegraph report :)

### Steps To Reproduce

Firstly, here's the bin file: https://litter.catbox.moe/g8io46.bin 

Let me know if you can't reproduce it with just the bin file and I'll try to make some more easy to follow and isolated steps.

What I'm doing is:
1. clone https://github.com/qutebrowser/qutebrowser/ && cd qutebrowser
2. create and activate a new virtualenv
3. install the requirements.txt in the qutebrowser folder, also memray
4. build Qt and PyQt and install PyQt to the virtualenv
5. run the script on https://github.com/qutebrowser/qutebrowser/issues/1476#issuecomment-1152868011 (but add `--native` to the memray call and change the PYTHON variable to point to the one in the virtualenv (why did I make that hardcoded?))
6. see the above error message after it completes

### Memray Version

1.7.0

### Python Version

3.11

### Operative System

Linux

**Comment by pablogsal** [comment] 2023-03-13 14:34
I think that assert that we have is too eager because we can be exactly in this situation: We have a bunch of Python frames but we don't have any known function in the native stack for some reason so we will have `len(hybrid_stack) - len(native_stack)` for the value of `hidx`.

@godlygeek thoughts?

**Comment by pablogsal** [comment] 2023-03-13 14:42
@toofar What distribution are you using? Maybe I can try to query the debuginfod servers to see where this is failing

**Comment by godlygeek** [comment] 2023-03-14 05:37
> We have a bunch of Python frames but we don't have any known function in the native stack for some reason so we will have `len(hybrid_stack) - len(native_stack)` for the value of `hidx`.

That's true (well, off-by-one - we'll have `hidx == len(hybrid_stack) - len(native_stack) - 1`). But, it's missing an important detail: for Python 3.10 and earlier, `len(hybrid_stack) == len(native_stack)`, which is why we've never seen this assertion fail before (and why I thought it was right when I added it). In 3.11, though, there are now non-entry frames, and `hybrid_stack` is longer than `native_stack` by the number of non-entry frames in the Python stack. If we fail to recognize a `_PyEval_EvalFrameDefault` call in Python 3.10 and earlier it only causes us to fill a native frame into `hybrid_stack` instead of a Python frame, but from 3.11 on it _also_ causes us to totally fail to insert any non-entry Python frames that were evaluated by that call to `_PyEval_EvalFrameDefault`, meaning we write fewer total entries into `hybrid_stack` than we meant to.

With that understanding of what went wrong, I'm pretty sure the fix for this is reasonably simple, and we just need to swap the `if` and the `assert` here:

https://github.com/bloomberg/memray/blob/af6cbcae43a2e7bb529c10eec6b9c3eef09fcd7e/src/memray/_memray.pyx#L239-L245

Currently we assert that `hidx == -1` (meaning we've filled an entry into every slot of the `hybrid_stack`) even if `pidx >= 0` (meaning we've failed to identify where some Python frame should have been put in the hybrid stack). In 3.10 and earlier that assumption holds, but in 3.11 it doesn't because of non-entry frames, so we should only check if `hidx == -1` in the case where we don't fail early because `pidx >= 0`.

**Closed** 2023-03-15 14:51 UTC
Labels: bug

**Comment by toofar** [comment] 2023-03-15 21:26
Thank you for the fix! I grabbed the wheels from CI and I'm getting a lot of C++ symbols showing now. Sorry for the lack of engagement in the meantime.

@pablogsal As for the interpreter debug symbols, it's just debian unstable. There is no python3-dbgsym package to install either so maybe they just don't ship them? Or maybe it's just unstable (although lots of other stuff in there does have debug symbols that debuginfod happily pulls down). Here's some container commands:

```bash
# memray complaining there are no debug symbols for the interpretor
docker run -i debian:unstable bash -s <<"EOF"
apt update
apt install -y python3-venv
export DEBUGINFOD_URLS=https://debuginfod.debian.net
python3 -m venv memray-test
. memray-test/bin/activate
pip3 install memray
printf "print('hi')\n" > smolprint.py
python3 -m memray run --native smolprint.py
python3 -m memray flamegraph `ls -tr | tail -n1`
EOF

# gdb saying "No debugging symbols found in python3" but happily pulling down
# ones for linked libraries
docker run -i debian:unstable bash -s <<"EOF"
apt update
apt install -y python3-venv gdb
export DEBUGINFOD_URLS=https://debuginfod.debian.net
printf "print('hi')\n" > smolprint.py
echo "set debuginfod enabled on" >> /etc/gdb/gdbinit
printf "r\nq\n" | gdb --args python3 ./smolprint.py
EOF
```

**Comment by pablogsal** [comment] 2023-03-16 01:01
> ```shell
> python3 -m memray flamegraph `ls -tr | tail -n1`
> ```

I think you are missing the debuginfod client installed. Using your reproducer and setting:

```
export DEBUGINFOD_VERBOSE=1
export DEBUGINFOD_PROGRESS=1
```

I get this when generating the flamegraph:

```
Trying to download debuginfo for /usr/bin/python3.11
Trying to download debuginfo for /lib/x86_64-linux-gnu/libm.so.6
Trying to download debuginfo for /lib/x86_64-linux-gnu/libz.so.1
Trying to download debuginfo for /lib/x86_64-linux-gnu/libexpat.so.1
Trying to download debuginfo for /lib/x86_64-linux-gnu/libc.so.6
Trying to download debuginfo for /lib64/ld-linux-x86-64.so.2
Trying to download debuginfo for /usr/lib/python3.11/lib-dynload/_typing.cpython-311-x86_64-linux-gnu.so
Trying to download debuginfo for /memray-test/lib/python3.11/site-packages/memray/_memray.cpython-311-x86_64-linux-gnu.so
Trying to download debuginfo for /memray-test/lib/python3.11/site-packages/memray/../memray.libs/liblz4-af1653fb.so.1.8.3
Trying to download debuginfo for /memray-test/lib/python3.11/site-packages/memray/../memray.libs/liblz4-af1653fb.so.1.8.3
Trying to download debuginfo for /memray-test/lib/python3.11/site-packages/memray/../memray.libs/libunwind-d5b5a318.so.8.0.1
Trying to download debuginfo for /memray-test/lib/python3.11/site-packages/memray/../memray.libs/libunwind-d5b5a318.so.8.0.1
Trying to download debuginfo for /lib/x86_64-linux-gnu/libdl.so.2
Trying to download debuginfo for /lib/x86_64-linux-gnu/libstdc++.so.6
Trying to download debuginfo for /lib/x86_64-linux-gnu/libgcc_s.so.1
Trying to download debuginfo for /lib/x86_64-linux-gnu/libpthread.so.0
Trying to download debuginfo for /usr/lib/python3.11/lib-dynload/mmap.cpython-311-x86_64-linux-gnu.so
Trying to download debuginfo for /usr/lib/python3.11/lib-dynload/termios.cpython-311-x86_64-linux-gnu.so
Trying to download debuginfo for /usr/lib/python3.11/lib-dynload/_decimal.cpython-311-x86_64-linux-gnu.so
Trying to download debuginfo for /usr/lib/python3.11/lib-dynload/_bz2.cpython-311-x86_64-linux-gnu.so
Trying to download debuginfo for /lib/x86_64-linux-gnu/libbz2.so.1.0
Trying to download debuginfo for /usr/lib/python3.11/lib-dynload/_lzma.cpython-311-x86_64-linux-gnu.so
Trying to download debuginfo for /lib/x86_64-linux-gnu/liblzma.so.5
Trying to download debuginfo for /usr/lib/python3.11/lib-dynload/_hashlib.cpython-311-x86_64-linux-gnu.so
Trying to download debuginfo for /lib/x86_64-linux-gnu/libcrypto.so.3
Trying to download debuginfo for /memray-test/lib/python3.11/site-packages/markupsafe/_speedups.cpython-311-x86_64-linux-gnu.so
Trying to download debuginfo for /usr/lib/python3.11/lib-dynload/_json.cpython-311-x86_64-linux-gnu.so
Trying to download debuginfo for /usr/bin/python3.11
```

But installing the client using:

```
apt-get install debuginfod
```

I get now:

```
Trying to download debuginfo for /usr/bin/python3.11
debuginfod_find_debuginfo ac175ec7666754cf818b271b4fdc2761ac6865f2
server urls "https://debuginfod.debian.net"
checking build-id
checking cache dir /root/.cache/debuginfod_client
not found No such file or directory (err=-2)
Trying to download debuginfo for /lib/x86_64-linux-gnu/libm.so.6
debuginfod_find_debuginfo 68ff1142b68506edd4169abf912874e35688b97b
server urls "https://debuginfod.debian.net"
checking build-id
checking cache dir /root/.cache/debuginfod_client
using timeout 90
init server 0 https://debuginfod.debian.net/buildid
url 0 https://debuginfod.debian.net/buildid/68ff1142b68506edd4169abf912874e35688b97b/debuginfo
query 1 urls in parallel
Downloading /header HTTP/1.1 404 Not Found
header Date: Thu, 16 Mar 2023 00:59:40 GMT
header Server: Apache/2.4.54 (Debian)
header Strict-Transport-Security: max-age=15768000
header Content-Length: 9
header Content-Type: text/plain
header
Downloading |
server response HTTP response code said error
url 0 The requested URL returned error: 404
not found No such file or directory (err=-2)
Trying to download debuginfo for /lib/x86_64-linux-gnu/libz.so.1
debuginfod_find_debuginfo 1f95d5498d283b79505861523e20b3db2afdf518
server urls "https://debuginfod.debian.net"
checking build-id
checking cache dir /root/.cache/debuginfod_client
using timeout 90
init server 0 https://debuginfod.debian.net/buildid
url 0 https://debuginfod.debian.net/buildid/1f95d5498d283b79505861523e20b3db2afdf518/debuginfo
query 1 urls in parallel
Downloading /header HTTP/1.1 200 OK
header Date: Thu, 16 Mar 2023 00:59:40 GMT
header Server: Apache/2.4.54 (Debian)
header Strict-Transport-Security: max-age=15768000
header Content-Length: 125448
header Cache-Control: public
header Last-Modified: Sat, 05 Nov 2022 12:24:46 GMT
header X-DEBUGINFOD-FILE: /usr/lib/debug/.build-id/1f/95d5498d283b79505861523e20b3db2afdf518.debug
header X-DEBUGINFOD-ARCHIVE: /srv/mirror/debian-debug/main/z/zlib/zlib1g-dbgsym_1.2.13.dfsg-1_amd64.deb
header X-DEBUGINFOD-SIZE: 125448
header Content-Type: application/octet-stream
header

....
```

Note we cover this here:

[memray-flamegraph-smolprint.py.2973.html
](https://bloomberg.github.io/memray/native_mode.html#debuginfod-integration)

Specifically this:

> To take advantage of debuginfod, you need two things:
>The debuginfod client library must be installed. This library allows you to query debuginfod servers. It is available in most Linux distributions (including Debian, Ubuntu, Fedora, Arch Linux, etc.) and can be installed with your package manager. For example, in Debian/Ubuntu:

**Comment by godlygeek** [comment] 2023-03-16 01:07
> I grabbed the wheels from CI

Whoa, I didn't know that was possible! TIL: On the "Summary" tab from a workflow run, you can scroll down to the bottom to a section called "Artifacts" and then download the built wheels for that CI run. I've never noticed that before!

> There is no python3-dbgsym package to install either so maybe they just don't ship them?

They do, the package is just called `python3-dbg` - I've tested with your reproducer, and that's enough to get Memray to stop giving its

> ⚠  No debug information was found for the Python interpreter  ⚠

warning, and remove the need for using `debuginfod`.
