### ISSUE TITLE
test_basic_attach fails on MacOS (M1 MacBook)

### ISSUE THREAD

**Issue by sjirwin** [bloomberg/memray#367] opened 2023-04-24 21:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the pytest unit test case `test_basic_attach[lldb]` fails on MacOS on M1 Mac (MacOS 13.3.1)

**Test case error message**
```
Debugger command line: lldb --batch -p 41524 --no-lldbinit -o 'expr char $libpath[]="/Users/sirwin/dev/memray/src/memray/_inject.abi3.so"' -o 'expr int $port=65448' -o 'expr void* $rtld_default=(void*)-2' -o 'expr int $rtld_now=2' --source /Users/sirwin/dev/memray/src/memray/commands/_attach.lldb
debugger return code: 1
debugger output:
(lldb) process attach --pid 41524
error: attach failed: attach failed (Not allowed to attach to process.  Look in the console messages (Console.app), near the debugserver entries when the attached failed.  The subsystem that denied the attach permission will likely have logged an informative message about why it was denied.)
```

**pytest-cov Environ**
```
tests/integration/test_attach.py::test_basic_attach[lldb] pytest-cov: Failed to setup subprocess coverage. Environ: {'COV_CORE_SOURCE': 'memray:tests', 'COV_CORE_CONFIG': '/Users/sirwin/dev/memray/pyproject.toml', 'COV_CORE_DATAFILE': '/Users/sirwin/dev/memray/.coverage'}
```

### Expected Behavior

Expect the test case to either pass or to be skipped on MacOS

### Steps To Reproduce

**Environment** 
- M1 Mac (I am using a M1 MacBook Pro)
- Running latest version of MacOS Ventura 13.3.1 (latest available at the moment)

**Setup build environment using instructions in `README.md`**
```
brew install lz4
python3 -m venv ../memray-env
source ../memray-env/bin/activate
export CFLAGS="-I$(brew --prefix lz4)/include" LDFLAGS="-L$(brew --prefix lz4)/lib -Wl,-rpath,$(brew --prefix lz4)/lib"
export MACOSX_DEPLOYMENT_TARGET="10.14" # not mentioned in README, but matches setting build_wheels.yml
```

**Build the project**
```
make dev-install
```

**Run the coverage target**
```
make pycoverage
```

**Error seen**
```
Debugger command line: lldb --batch -p 41524 --no-lldbinit -o 'expr char $libpath[]="/Users/sirwin/dev/memray/src/memray/_inject.abi3.so"' -o 'expr int $port=65448' -o 'expr void* $rtld_default=(void*)-2' -o 'expr int $rtld_now=2' --source /Users/sirwin/dev/memray/src/memray/commands/_attach.lldb
debugger return code: 1
debugger output:
(lldb) process attach --pid 41524
error: attach failed: attach failed (Not allowed to attach to process.  Look in the console messages (Console.app), near the debugserver entries when the attached failed.  The subsystem that denied the attach permission will likely have logged an informative message about why it was denied.)
```

### Memray Version

1.7.0

### Python Version

3.11

### Operating System

macOS

### Anything else?

the issue seems related the note below which is found in the Apple Developer article [Embedding a command-line tool in a sandboxed app](https://developer.apple.com/documentation/xcode/embedding-a-helper-tool-in-a-sandboxed-app)

> The absence of the `com.apple.security.get-task-allow` entitlement means that you won’t be able to debug your tool. If you need to debug, create a new command-line tool target, one that’s not sandboxed, specifically for debugging. Be warned, however, that this target may behave differently from the normal tool target because it’s not running in a sandbox.

I did not find a way to add the `com.apple.security.get-task-allow` entitlement for projects compiled on the command line (i.e., outside of the XCode IDE)

**Comment by pablogsal** [comment] 2023-06-20 15:36
I cannot reproduce this on my M1 mac:

```
memray on  main [$?⇕] via 🐳 desktop-linux took 4s
❯ python -m pytest tests -k test_basic_attach -v
==================================================================================== test session starts =====================================================================================
platform darwin -- Python 3.11.1, pytest-7.2.0, pluggy-1.0.0 -- /Users/pgalindo3/.pyenv/versions/memray/bin/python
cachedir: .pytest_cache
rootdir: /Users/pgalindo3/github/memray, configfile: pyproject.toml
plugins: xdist-3.1.0, typeguard-2.13.3, cov-4.0.0, pystack-faulthandler-0.1.0
collected 562 items / 560 deselected / 2 selected

tests/integration/test_attach.py::test_basic_attach[lldb] PASSED                                                                                                                       [ 50%]
tests/integration/test_attach.py::test_basic_attach[gdb] SKIPPED (a supported gdb debugger isn't installed)                                                                            [100%]

==================================================================
```

so I am going to close this issue until we have a better reproducer for this.

**Closed by pablogsal** 2023-06-20 15:36 UTC
Labels: bug
