### ISSUE TITLE
memray with setproctitle causes some kind of hang

### ISSUE THREAD

**Issue by mattp-** [bloomberg/memray#275] opened 2022-12-19 18:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

unsure what exactly is going on here, but a combination of getproctitle+setproctitle causes a hang on serialization, reproduced on linux py3.7.6 and py3.11. 

https://pypi.org/project/setproctitle/

### Expected Behavior

memray works

### Steps To Reproduce

```
memray run -c 'import setproctitle; setproctitle.setproctitle( setproctitle.getproctitle() )'                  
```

### Memray Version

1.3.2

### Python Version

3.7, 3.11

### Operative System

Linux

### Anything else?

this was reduced from trying to use memray with https://github.com/saltstack/salt

**Comment by pablogsal** [comment] 2022-12-19 18:26
Hi @mattp- and thanks for opening this issue.

Unfortunately I cannot reproduce it on my side:

```
❯ memray run -c 'import setproctitle; setproctitle.setproctitle( setproctitle.getproctitle() )'

Writing profile results into memray-string.33389.bin
[memray] Successfully generated profile results.

You can now generate reports from the stored allocation records.
Some example commands to generate reports:

/home/pablogsal/.pyenv/versions/3.10.1/envs/memray/bin/python -m memray flamegraph memray-string.33389.bin
```

This is the version that I am using:

```
pip freeze | grep setproctitle
setproctitle==1.3.
```

For us to help, you need to give us a better reproducer. If this only happens on specific Linux distros, could you give us a Dockerfile where you can reproduce the issue?

**Comment by mattp-** [comment] 2022-12-19 18:27
hm, thats odd. let me see

**Comment by pablogsal** [comment] 2022-12-19 18:30
I tried to reproduce it in a Ubuntu 20.04 docker container but I also failed to reproduce:

```
root@7e56a33f144b:/# python3.8 -m pip install memray setproctitle
Collecting memray
  Downloading memray-1.5.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 12.7 MB/s
Collecting setproctitle
  Downloading setproctitle-1.3.2-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (31 kB)
Collecting jinja2
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 156.5 MB/s
Collecting rich>=11.2.0
  Downloading rich-12.6.0-py3-none-any.whl (237 kB)
     |████████████████████████████████| 237 kB 160.7 MB/s
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting commonmark<0.10.0,>=0.9.0
  Downloading commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
     |████████████████████████████████| 51 kB 17.3 MB/s
Collecting typing-extensions<5.0,>=4.0.0; python_version < "3.9"
  Downloading typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting pygments<3.0.0,>=2.6.0
  Downloading Pygments-2.13.0-py3-none-any.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 158.4 MB/s
Installing collected packages: MarkupSafe, jinja2, commonmark, typing-extensions, pygments, rich, memray, setproctitle
Successfully installed MarkupSafe-2.1.1 commonmark-0.9.1 jinja2-3.1.2 memray-1.5.0 pygments-2.13.0 rich-12.6.0 setproctitle-1.3.2 typing-extensions-4.4.0
root@7e56a33f144b:/#  memray run -c 'import setproctitle; setproctitle.setproctitle( setproctitle.getproctitle() )'
Writing profile results into memray-string.3862.bin
Memray WARNING: Correcting symbol for malloc from 0x425490 to 0x7f0cbea870e0
Memray WARNING: Correcting symbol for free from 0x425910 to 0x7f0cbea876d0
Memray WARNING: Correcting symbol for aligned_alloc from 0x7f0cbe2fbbf0 to 0x7f0cbea88250
[memray] Successfully generated profile results.

You can now generate reports from the stored allocation records.
Some example commands to generate reports:

/usr/bin/python3.8 -m memray flamegraph memray-string.3862.bin
```

**Comment by pablogsal** [comment] 2022-12-19 18:38
Tried also on a different kernel + Ubuntu and also cannot repro:

```
$ uname -a
Linux buildbot 5.4.0-86-generic #97-Ubuntu SMP Fri Sep 17 19:19:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ python -m venv venv
/usr/bin/python: No module named venv
pablogsal@buildbot:~$ python3 -m venv venv
source venv/bin/activapablogsal@buildbot:~$ source venv/bin/activate
(venv) pablogsal@buildbot:~$ python -m pip install memray setproctitle
Collecting memray
  Downloading memray-1.5.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 14.1 MB/s
Collecting setproctitle
  Downloading setproctitle-1.3.2-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (31 kB)
Collecting rich>=11.2.0
  Downloading rich-12.6.0-py3-none-any.whl (237 kB)
     |████████████████████████████████| 237 kB 36.5 MB/s
Collecting jinja2
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 43.6 MB/s
Collecting pygments<3.0.0,>=2.6.0
  Downloading Pygments-2.13.0-py3-none-any.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 46.8 MB/s
Collecting typing-extensions<5.0,>=4.0.0
  Downloading typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting commonmark<0.10.0,>=0.9.0
  Downloading commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
     |████████████████████████████████| 51 kB 10.8 MB/s
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Installing collected packages: typing-extensions, pygments, MarkupSafe, commonmark, rich, jinja2, setproctitle, memray
Successfully installed MarkupSafe-2.1.1 commonmark-0.9.1 jinja2-3.1.2 memray-1.5.0 pygments-2.13.0 rich-12.6.0 setproctitle-1.3.2 typing-extensions-4.4.0
WARNING: You are using pip version 21.1.1; however, version 22.3.1 is available.
You should consider upgrading via the '/home/pablogsal/venv/bin/python -m pip install --upgrade pip' command.

(venv)~$ python
Python 3.8.12 (default, Sep 10 2021, 00:16:05)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
(venv) ~$ memray run -c 'import setproctitle; setproctitle.setproctitle( setproctitle.getproctitle() )'
Writing profile results into memray-string.1564221.bin
Memray WARNING: Correcting symbol for malloc from 0x422ec0 to 0x7fb252eb30e0
Memray WARNING: Correcting symbol for free from 0x423330 to 0x7fb252eb36d0
Memray WARNING: Correcting symbol for aligned_alloc from 0x7fb252611bf0 to 0x7fb252eb4250
[memray] Successfully generated profile results.

You can now generate reports from the stored allocation records.
Some example commands to generate reports:

/home/pablogsal/venv/bin/python -m memray flamegraph memray-string.1564221.bin
````

**Comment by pablogsal** [comment] 2022-12-19 18:49
Same result with older kernel and older ubuntu:

```
$(venvmemray) pablogsal@speed-python:~$ uname -a
Linux speed-python 4.15.0-159-generic #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$(venvmemray) pablogsal@speed-python:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

$memray run -c 'import setproctitle; setproctitle.setproctitle( setproctitle.getproctitle() )'
Writing profile results into memray-string.16851.bin
Memray WARNING: Correcting symbol for malloc from 0x422e00 to 0x7fd9d9d71140
Memray WARNING: Correcting symbol for free from 0x423270 to 0x7fd9d9d71a30
Memray WARNING: Correcting symbol for aligned_alloc from 0x7fd9d88e1bf0 to 0x7fd9d9d731d0
[memray] Successfully generated profile results.

You can now generate reports from the stored allocation records.
Some example commands to generate reports:

/home/pablogsal/venvmemray/bin/python -m memray flamegraph memray-string.16851.bin
```

**Comment by mattp-** [comment] 2022-12-19 18:51
ya, I'm trying and failing to create a reproducible container based test of this outside of my workstation, not quite sure exactly whats happening. I thought it was easily reproachable, evidently not :) I'll keep trying, but in the meantime please don't waste any more time on this on the chance its something stupid with my setup. thanks

**Comment by pablogsal** [comment] 2022-12-19 18:53
👍 

If you manage to get it hanging, please take a stacktrace with `gdb` or `lldb` (`thread apply bt all` in `gdb`). Maybe we can know then if is memray or not.

We like to get the bugtracker clean so I am going to close this issue for now, but **please, re-open the issue if you manage to reproduce it or if you have more information**.

**Closed by pablogsal** 2022-12-19 18:53 UTC
Labels: bug
