### ISSUE TITLE
Environment variable to mute the macOS warning

### ISSUE THREAD

**Issue by tonybaloney** [bloomberg/memray#254] opened 2022-11-16 22:55 UTC
### Is there an existing proposal for this?

- [X] I have searched the existing proposals

### Is your feature request related to a problem?

https://github.com/bloomberg/memray/blob/ab31d4c995e83b0bf6020958d2a12903d2b322db/src/memray/_memray.pyx#L374-L376 writes to stderr when running on macOS

My tests monitor stderr and fail when running with memray because stderr has unexpected output (the warning message)

### Describe the solution you'd like

The ability to have a flag/environment variable to mute this warning message

**Comment by godlygeek** [comment] 2022-11-16 23:29
Duplicate of #194 (which has #250 as a proposed solution).

We're trying to avoid adding an environment variable for suppressing warnings, since it requires manual steps to avoid the problem from the part of people using `pytest-memray`. That said, there are some drawbacks to just moving where we print the warning, too...

**Closed** 2022-11-16 23:52 UTC
Labels: enhancement
